### ISSUE TITLE
another XSS in the tags view

### ISSUE THREAD

**Issue by the94air** [jacurtis/laravel-blog-tutorial#10]
Also the same [XXS problem](https://github.com/jacurtis/laravel-blog-tutorial/issues/1) in the tag `tags.show` view `$tag->name`

**Comment by jacurtis** [comment]
Thank you. This has changed across newer versions, so depending on the laravel version people are using it can cause some problems. So i will keep this problem in the codebase, but if you are using this on production then it needs to be fixed.
