### ISSUE TITLE
Blog Comments Date Error

### ISSUE THREAD

**Issue by waqardm** [jacurtis/laravel-blog-tutorial#11]
Code is currently

`						<img src="{{ "https://www.gravatar.com/avatar/" . md5(strtolower(trim($comment->email))) . "?s=50&d=monsterid" }}" class="author-image">
						<div class="author-name">
							<h4>{{ $comment->name }}</h4>
							<p class="author-time">{{ date('F nS, Y - g:iA' ,strtotime($comment->created_at)) }}</p>
						</div>
`

You have use 'n' which is the numeric representation for month, correct one should be 'd' as noted below:

`						<img src="{{ "https://www.gravatar.com/avatar/" . md5(strtolower(trim($comment->email))) . "?s=50&d=monsterid" }}" class="author-image">
						<div class="author-name">
							<h4>{{ $comment->name }}</h4>
							<p class="author-time">{{ date('F dS, Y - g:iA' ,strtotime($comment->created_at)) }}</p>
						</div>
`

**Comment by jacurtis** [comment]
Nice catch. Thank you. Correct that it should be:

```
date('F dS, Y - g:iA' ,strtotime($comment->created_at))
```

**Comment by jacurtis** [comment]
What file does this happen in and i can change it. Or you can submit a PR and ill approve it.

**Comment by waqardm** [comment]
I will submit a PR if it's OK, need to learn so 2 birds...

**Comment by waqardm** [comment]
Hey, just submitted the PR #12

**Comment by jacurtis** [comment]
Merged the PR, thanks
