### ISSUE TITLE
geeting error

### ISSUE THREAD

**Issue by alish2202** [jacurtis/laravel-blog-tutorial#14]
PHP Warning:  require_once(C:\xampp\htdocs\blog\vendor/composer/autoload_real.ph
p): failed to open stream: No such file or directory in C:\xampp\htdocs\blog\ven
dor\autoload.php on line 5

Warning: require_once(C:\xampp\htdocs\blog\vendor/composer/autoload_real.php): f
ailed to open stream: No such file or directory in C:\xampp\htdocs\blog\vendor\a
utoload.php on line 5
PHP Fatal error:  require_once(): Failed opening required 'C:\xampp\htdocs\blog\
vendor/composer/autoload_real.php' (include_path='.;C:\xampp\php\PEAR') in C:\xa
mpp\htdocs\blog\vendor\autoload.php on line 5

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\blog\vendo
r/composer/autoload_real.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\h
tdocs\blog\vendor\autoload.php on line 5

**Comment by marufmax** [comment]
Did you install composer properly?

**Comment by alish2202** [comment]
issue is solved out.
there is vendor files are missing.

thanks for replay.. 👍

**Comment by marufmax** [comment]
Then please close the issue

**Comment by jacurtis** [comment]
Run `composer install` in your terminal to install dependencies and it will solve your issue. Also make sure you have installed composer on your computer before you run the command.

Closing the issue.
