### ISSUE TITLE
Getting Error of non object property when i try to put Category title in Blog. 

### ISSUE THREAD

**Issue by mansoor090** [jacurtis/laravel-blog-tutorial#15]
Hi, I am getting an error of non object property 

       @foreach( $posts as $post)
     .....
     ....
            <a href="singlepage.html"><img src="images/2.jpg" class="img-responsive" alt=""/>{{ 
           $post->$category->id}}</a>
    .... 
     ....

here is my controller part: 

	  $posts= Post::paginate(10);
	
         $categories = Category::all();

         $tags = Tag::all();
         $tags2 = array();
         foreach ($tags as $tag) {
             $tags2[$tag->id] = $tag->name;
         }

	return view('blog.index')->withPosts($posts)->withCategory($categories)->withTags($tags2);

}

**Comment by mansoor090** [comment]
when i remove 
     $post->$category->id .
 page loads fine .

**Comment by jacurtis** [comment]
`$post->category()->id` would be the correct syntax you are looking for. 

That is assuming you named your relationship "category" and not "categories" which is the more common way to do it. If youre relationship is "categories" then the correct syntax would be `$post->categories()->id`
