### ISSUE TITLE
blog/single.blade.php

### ISSUE THREAD

**Issue by sfavorite** [jacurtis/laravel-blog-tutorial#16]
Hey Alex,

This isn't an issue so much as an improvement (hopefully). In the file 

/resources/views/blog/single.blade.php 

you can change the following...

`<?php $titleTag = htmlspecialchars($post->title); ?>
@section('title', "| $titleTag")
`
to...

`@section('title')
    | {{ $post->title }}
@stop
`
You will get the same output. 

Hope this helps.

**Comment by lloricode** [comment]
this so simple as not so complicated :) :+1:

**Comment by jacurtis** [comment]
Thanks
