### ISSUE TITLE
Why my posts can delete other users?

### ISSUE THREAD

**Issue by dulebamboocha** [jacurtis/laravel-blog-tutorial#17]
Hi, Alex,
first of all I can't believe that there are people like you, you are wasting your time to teach others and you are doing it for free. You are awesome, man. I have been learn so much from you and I wish that I can do something more than just say 'thank you'. 
I almost went through all yours 'How to Build a Blog with Laravel 5 Series' and I figured out that when some user create post then other users can delete and edit his post. In other words said, all posts of some user appear to other users in their account and there they can delete and edit that posts which means that anyone can delete anyone's post. And I think it should not work that way. Is there some solution for that? 
Thank you very much for all, you are amazing!!!

**Comment by lloricode** [comment]
This is good idea,

if you what to do that, you will add a reference `posts.user_id` from `users.id` to a `posts`
then check if the owner of post is equal of current logged_in user

```php
// in post migration
 
Schema::create('posts', function (Blueprint $table) {
            // ...
            $table->integer('user_id')->unsigned();
            $table->foreign('user_id')->references('id')->on('users');
            // ...
});
```

To get a id of current logged user
```php
$current_logged_user_id= Auth::user()->id;
    
//so posts has alredy user_id af miragrate, now you can check the user if they own a posts
if( Auth::user()->id === $post->user->id ){
    //delete
    //update
    //etc
}
else
{
    //invalid access
}

```

**Comment by sh1hab** [comment]
@lloricode shouldn't it be Schema::table('posts',

**Comment by lloricode** [comment]
@sh1hab hmm it is in migration it depend on you :) , in my case I create table

you can use

```php
Schema::table('posts',
```

if table already exist :)

**Comment by dulebamboocha** [comment]
Thanks both of you for help! I created new migration like you said, @lloricode with suggestion like @sh1hab  said, and here I stopped and then I tried to create new post with some user but I'm getting this error: 
QueryException in Connection.php line 669: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`jacurtis`.`posts`, CONSTRAINT `posts_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))

**Comment by lloricode** [comment]
@dulebamboocha hmmm did you run `php artisan migrate`?

so if yes?

put this with all `down` function inside of you migration if has relation something like this
`$table->foreign('user_id')->references('id')->on('users');`

```php
public function down()
{ 
      // Just add this to drop existing reference
      Schema::table('comments', function (Blueprint $table) {
            $table->dropForeign(['post_id']);
      });

      Schema::dropIfExists('comments');
}
```

:)

**Comment by dulebamboocha** [comment]
Thanks for reply, @lloricode !
Yes, I migrated. I do it what you said, and now I don't have table 'comments' anymore and still getting same error

**Comment by lloricode** [comment]
@dulebamboocha ahw, Im sorry I forgot to say that just replace the name of table depend on you migration file

in your problem
```
QueryException in Connection.php line 669: SQLSTATE[23000]: Integrity constraint violation: 1452 
Cannot add or update a child row: a foreign key constraint fails (jacurtis.posts, CONSTRAINT 
posts_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id))
```

I think your file in in `posts` migration

so this will work? try
```php
public function down()
{ 
      // Just add this to drop existing reference
      Schema::table('posts', function (Blueprint $table) {
            $table->dropForeign(['user_id']);
      });

      Schema::dropIfExists('posts');
}

```

best regards :+1:

**Comment by lloricode** [comment]
I forgot

`php artisan migrate:refresh`
rather than
`php artisan migrate`
to run `down` function in every migration file

**Comment by jacurtis** [comment]
Thanks, i was going to mention doing a migration refresh which undo all your migrations and then run them again.

**Comment by lloricode** [comment]
Byy the way , @jacurtis Thank for the youtube play-list, and now I can create a laravel app :100:

**Comment by jacurtis** [comment]
Glad youve been able to learn Laravel. Ill be updating the series for Laravel 5.5.

**Comment by dulebamboocha** [comment]
I did migrate:refresh earlier, and planning to do that again. I remebered that from one of Alex's tutorial. You are awesome. Many, many thanks for help. Just one question if I'm not bothering you. I' m newbie in laravel and in php so where I need to put the code to check if the owner of post is equal of current logged_in user. In PostsController or..? Thank you very much!!!

**Comment by lloricode** [comment]
hmmmm. so dificult to explain, @dulebamboocha . I will link to you the code,

my plan is made a Pull request in here but, @jacurtis mark this as unsupported enhancement, so I will just make this to my repo

**Comment by dulebamboocha** [comment]
If you do that, @lloricode  I will be so grateful to you. Thank you so much, @lloricode :-)

**Comment by jacurtis** [comment]
I don't want to put additions to this code if there isn't video to support it. The series is very popular and adding code that isn't explained through the video series confuses people, so i want the code here to only reflect what is explained in the video series. So while youre welcome to discuss it here, i dont want to pull it into the codebase because it isn't in a video to explain it.

To do what you are looking for you will have to add logic to several elements of the project to get it to work together.

1. As noted by @lloricode, you need to store the owner of a post in the DB in order to know who wrote the post later when you want to authorize a user. Create the migration to add a column in the DB which will store the user_id of the user that "owns" the post.
1. Create a relationship with that column in the model. A post belongs to a user and a user has many posts. It is a one-to-many relationship and you will want to identify the relationship in the model so you can easily call it later.
1. In the `save()` method of a post, you also want to make sure that you store the user's id in the new column, so that the relationship of the post owner can be defined.
1. Finally add some logic in your `show()`, `edit()`, `update()`, and `destroy()` methods to check if the current user is the one that also owns the post. There are many ways to do this:
    1. The easy way is to add a basic `if` statement at the top of each method to compare the current user (probably using `Auth::user()->id` to the user id of the relationship we defined of the posts owner.
    1. A better way would be to define middleware which is basically the same thing as what is described above, but wrapped in middleware so you don't have to repeat yourself
    1. The best way would be to use the [Authorization api ](https://laravel.com/docs/5.4/authorization)in Laravel to define user roles and protect it using the middleware already created such as `$this->middleware('can:view_post', $post->id)`

Going into much more detail would really be a full written tutorial. But hopefully this gives you a sense for the direction to take to make this happen.

**Comment by lloricode** [comment]
Thanks @jacurtis :)
@dulebamboocha , still on going. wait until an hour :)

**Comment by lloricode** [comment]
@dulebamboocha [heres](https://github.com/lloricode/laravel-blog/commit/c31b737496de880d9453b0477fb4d82bfcb8be69) the logic :)

**Comment by lloricode** [comment]
@dulebamboocha  just incase I update the repo, just click [branch](https://github.com/lloricode/laravel-blog/tree/user-own-posts) in specific commit :)

**Comment by dulebamboocha** [comment]
Thank you so much, @lloricode , I don't know how to thank you!!! I'm going to try now and I will let you know soon! Thank you, @lloricode !!!

**Comment by lloricode** [comment]
my pleasure @dulebamboocha :) :+1:  Thanks.

**Comment by dulebamboocha** [comment]
@lloricode You are awesome!!! Everything is make the job!!! I had a problem, and that's why it took me to long to answer you, when trying to implement your code to Alex's repo. Problem was with route, because you add a link for registration in login.blade.php but I solved that. Like I said, I'm newbie in php and laravel and It will take a long time until I learn more and until I can call myself a developer. But thanks to you and @jacurtis  and all other people like you, my path is much easier than some others had! Thank you so much @lloricode !!! Have a nice day!!!

**Comment by lloricode** [comment]
Thanks @jacurtis, and @dulebamboocha :)

@dulebamboocha keep up the passion of our skills,

Happy Codings! :1st_place_medal:

**Comment by lloricode** [comment]
hi @jacurtis, im back, and got a senior software developer position, and  have a 4 years experience in my first job in company, I never forget where did i first run laravel with version 5.4, its been a long journey and still continue,

edit: thank you very much
