### ISSUE TITLE
Migrate:refresh

### ISSUE THREAD

**Issue by vukasinzurzevic** [jacurtis/laravel-blog-tutorial#5]
I finished project and when I try to do php artisan migrate:refresh I get the message:  Call to undefined method Illuminate\Database\Schema\MySqlBuilder::dropForeign()

**Comment by jacurtis** [comment]
You have to drop your foreign key index BEFORE you drop your column. In your migration edit it so that the foreign key is droppped first and then the column is dropped next. When creating the column, you must do it opposite. So create the column first and then create the foreign key second.
