### ISSUE TITLE
New post BelongsToMany error

### ISSUE THREAD

**Issue by maximvlc** [jacurtis/laravel-blog-tutorial#6]
very good job and a great help, thanks
but I found a small error in the code, you may have passed
when you create a new post and leave blank tags or just a tag jumps error
Type error: Argument 1 passed to Illuminate \ Database \ Eloquent \ Relations \ BelongsToMany :: formatSyncList () must be of the type array, null given, called in

**Comment by maximvlc** [comment]
and in view 'blog.index'
change $post->id to $post->slug
`<a href="{{ route('blog.single', $post->slug) }}" class="btn btn-primary">Read More</a>`

**Comment by apratik46** [comment]
how to fix this error
Argument 1 passed to Illuminate \ Database \ Eloquent \ Relations \ BelongsToMany :: formatSyncList ()
that you mentioned before 
please help

**Comment by waqardm** [comment]
@maximvlc just add `'tags' => 'required',` to your store and update functions.
