### ISSUE TITLE
whenever new post is created with no tags errors occur

### ISSUE THREAD

**Issue by apratik46** [jacurtis/laravel-blog-tutorial#8]
ErrorException in BelongsToMany.php line 866:
Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::formatSyncList() must be of the type array, null given, called in C:\xampp\htdocs\blog\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php on line 831 and defined

**Comment by waqardm** [comment]
@apratik46 can you share your code please?
