### ISSUE TITLE
select2 is not working.

### ISSUE THREAD

**Issue by DaKe-Zhang** [jacurtis/laravel-blog-tutorial#9]
Trying to use select2. always get 
![image](https://cloud.githubusercontent.com/assets/16347790/23338706/a826aca0-fbd7-11e6-8aeb-4a81bb9d3cc4.png)

why is that?

**Comment by waqardm** [comment]
@DaKeZhang7412 this seems like an issue with your implementation. Can you share your code?

**Comment by DaKe-Zhang** [comment]
@Waqardm I copied the code from Alex code. so it's exactly same as his. and that's why I am frustrating.

**Comment by Waqardm** [comment]
@DaKeZhang7412 yes i just checked mine and its the same. Just an oversight by Alex I guess, but easily fixed. Well spotted though!

**Comment by waqardm** [comment]
I had the same issue and isn't anything major, if u can share the code I can have a look at it for you?

**Comment by DaKe-Zhang** [comment]
@Waqardm  [clickhere to see my reposite](https://github.com/DaKeZhang7412/laravel-blog-tutorial/blob/master/resources/views/posts/create.blade.php)

**Comment by waqardm** [comment]
You seem to be missing the curley braces for the dropdown:

`{{ Form::select('tags[]', $tags, null, ['class' => 'select2-multi form-control', 'multiple' => 'multiple']) }}`

also, it should be `"multiple" = "multiple"` where as you didn't put the first 'multiple' in quote marks.

Hope that resolves it!

**Comment by waqardm** [comment]
@DaKeZhang7412 did it work?

**Comment by DaKe-Zhang** [comment]
@Waqardm 

sorry I tried that.

That was not the problem is. FYI, The "multiple" dose not need quote marks when it in the select property.

**Comment by Luthr** [comment]
Could try replacing your 'Foreach loop' with a form select:

	```
{{ Form::label('tags', 'Tags:', ['class' => 'form-spacing-top']) }}
        {{ Form::select('tags[]', $tags, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) }}
```

**Comment by KharChin** [comment]
Select2 requires jQuery library. Insert this code in your xxxxx.blade.php before the Select2 code:

<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
